name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:

  lint:
    uses: exbotanical/.github/.github/workflows/pnpm_script_run.yml@master
    with:
      script_name: lint

  unit_test:
    uses: exbotanical/.github/.github/workflows/pnpm_script_run.yml@master
    with:
      script_name: test
